{% set name = "rapid-pe" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapid_pe-{{ version }}.tar.gz
  sha256: 75912c695c9f9e1f9dc6492b2002703b194c98c17ffc2faeefb3436dfcb69523

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - bilby
    - h5py
    - healpy
    - lalsuite
    - ligo.skymap
    - lscsoft-glue
    - matplotlib-base
    - numpy
    - python
    - python-ligo-lw
    - scikit-learn
    - scipy
    - six

test:
  imports:
    - rapid_pe
  commands:
    - pip check
  requires:
    - pip
    # forcibly install uptodate xarray so that pip check doesn't choke on arviz
    - xarray >=0.21.0

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe/
  summary: 'RapidPE: The original low-latency gravitational wave parameter estimation code.'
  license: GPL-2.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - dwysocki
